version: '3.2'

services:
  tmax-dak:
    image: harbor.tmaxos.net/infra/tmax-dak:1.0.1
    container_name: tmax-dak-cont
    hostname: tos-ftp-master
    depends_on:
      - "tmax-uploadqueue"
    volumes:
      - .:/home/dak/dak
      - /srv/dak-data:/var/lib/postgresql/data
      - /srv/dak:/srv/dak
      - /srv/upload.tmaxos.net:/srv/upload.tmaxos.net
    ports:
      - "80:80"
  tmax-uploadqueue:
    image: harbor.tmaxos.net/infra/tmax-uploadqueue:1.0.1
    network_mode: "host"
    container_name: tmax-uploadqueue-cont
    hostname: uploadqueue
    volumes:
      - /srv/upload.tmaxos.net:/srv/upload.tmaxos.net
